import { defineStore } from 'pinia';
import type { DrillCompletion, DrillConfig, UserStats } from '~/types/drill';

export const useDrillStore = defineStore('drill', {
    state: () => ({
        drills: [] as DrillConfig[],
        completions: [] as DrillCompletion[],
    }),

    getters: {
        userStats: (state): UserStats =>
        {
            const totalDrillsCompleted = state.completions.length;

            const completionsByCategory: Record<string, number> = {};
            state.completions.forEach(completion =>
            {
                const drill = state.drills.find(d => d.id === completion.drillId);
                if (drill)
                {
                    completionsByCategory[drill.category] = (completionsByCategory[drill.category] || 0) + 1;
                }
            });

            return {
                totalDrillsCompleted,
                completionsByCategory,
                recentCompletions: state.completions.slice(-10).reverse(),
                favoriteDrillIds: [],
            };
        },

        getDrillsByCategory: (state) => (category: string) =>
        {
            return state.drills.filter(drill => drill.category === category);
        },

        isCompleted: (state) => (drillId: string) =>
        {
            return state.completions.some(c => c.drillId === drillId);
        },
    },

    actions: {
        async initDrills()
        {
            // Real field training drills with YouTube videos
            this.drills = [
                // PASSING DRILLS
                {
                    id: 'passing-triangles',
                    name: 'Passing Triangles',
                    category: 'passing',
                    difficulty: 'beginner',
                    description: 'Master the fundamentals of passing with this classic triangle drill',
                    instructions: [
                        'Set up 3 cones in a triangle shape, 5-7 meters apart',
                        'Place one player at each cone',
                        'Pass the ball to your right and follow your pass',
                        'Receive with your back foot, pass with your front foot',
                        'Keep the ball moving quickly and accurately',
                    ],
                    icon: '🔺',
                    color: '#3b82f6',
                    duration: 10,
                    playersNeeded: '3',
                    spaceRequired: '10x10m',
                    videoUrl: 'Z2ckosM2pWg', // Replace with actual SwitchedOn video ID
                    equipment: ['3 cones', '1 ball'],
                    keyPoints: [
                        'Use the inside of your foot for accuracy',
                        'Look up before passing',
                        'Communicate with teammates',
                        'Move after you pass',
                    ],
                    progressions: [
                        'Add a second ball',
                        'Pass and move to different cone',
                        'One-touch passing only',
                        'Add defensive pressure',
                    ],
                    benefits: [
                        'Improves passing accuracy and technique',
                        'Develops communication skills with teammates',
                        'Enhances spatial awareness and movement off the ball',
                        'Builds first touch control under pressure',
                        'Increases stamina through constant movement',
                    ],
                },
                {
                    id: 'rondo-4v1',
                    name: 'Rondo 4v1',
                    category: 'passing',
                    difficulty: 'intermediate',
                    description: 'Build passing under pressure with this essential rondo drill',
                    instructions: [
                        'Mark out a 10x10m square with cones',
                        '4 players on the outside, 1 defender in the middle',
                        'Outside players keep possession with max 2 touches',
                        'Defender tries to intercept or force error',
                        'If defender wins ball, they switch with player who lost it',
                    ],
                    icon: '⭕',
                    color: '#3b82f6',
                    duration: 15,
                    playersNeeded: '5',
                    spaceRequired: '10x10m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['4 cones', '1 ball', '2 colored bibs'],
                    keyPoints: [
                        'Quick decision making',
                        'Create passing angles',
                        'Body position to receive',
                        'Scan before receiving',
                    ],
                    progressions: [
                        'Reduce to 1-touch',
                        'Make space smaller',
                        'Add second defender',
                        '5v2 variation',
                    ],
                },

                // SHOOTING DRILLS
                {
                    id: 'finishing-in-the-box',
                    name: 'Finishing in the Box',
                    category: 'shooting',
                    difficulty: 'intermediate',
                    description: 'Improve your finishing from different angles inside the penalty area',
                    instructions: [
                        'Set up 5 cones around the penalty area edge',
                        'Start at first cone with a ball',
                        'Dribble towards goal and shoot',
                        'Retrieve ball and move to next cone',
                        'Vary your finish: power, placement, curl',
                    ],
                    icon: '🥅',
                    color: '#ef4444',
                    duration: 15,
                    playersNeeded: '1-2',
                    spaceRequired: 'Penalty area',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['5 cones', '5+ balls', '1 goal'],
                    keyPoints: [
                        'Strike through the center of the ball',
                        'Keep your head down',
                        'Use your laces for power',
                        'Inside foot for placement',
                    ],
                    progressions: [
                        'Add a defender',
                        'Receive a pass first',
                        'One-touch finishing',
                        'Add time pressure',
                    ],
                },

                // DRIBBLING DRILLS
                {
                    id: 'cone-weave',
                    name: 'Cone Weave Dribbling',
                    category: 'dribbling',
                    difficulty: 'beginner',
                    description: 'Develop close control and quick feet',
                    instructions: [
                        'Set up 6-8 cones in a straight line, 1 meter apart',
                        'Dribble through the cones using both feet',
                        'Keep the ball close to your feet',
                        'Accelerate between cones',
                        'At the end, turn and dribble back',
                    ],
                    icon: '🎯',
                    color: '#f59e0b',
                    duration: 10,
                    playersNeeded: '1+',
                    spaceRequired: '15x5m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['6-8 cones', '1 ball per player'],
                    keyPoints: [
                        'Use the outside and inside of both feet',
                        'Keep head up between touches',
                        'Small touches for control',
                        'Accelerate out of each turn',
                    ],
                    progressions: [
                        'Time yourself',
                        'Use only one foot',
                        'Add specific moves at each cone',
                        'Dribble backwards',
                    ],
                },

                // AGILITY DRILLS
                {
                    id: 'ladder-drills',
                    name: 'Agility Ladder',
                    category: 'agility',
                    difficulty: 'beginner',
                    description: 'Improve footwork, coordination, and speed',
                    instructions: [
                        'Lay out an agility ladder (or mark 10 squares with tape/chalk)',
                        'Perform various footwork patterns through the ladder',
                        'Start with basic: one foot in each square',
                        'Progress to more complex patterns',
                        'Repeat 5-10 times',
                    ],
                    icon: '⚡',
                    color: '#8b5cf6',
                    duration: 10,
                    playersNeeded: '1+',
                    spaceRequired: '10x2m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Agility ladder or chalk/tape'],
                    keyPoints: [
                        'Stay on balls of feet',
                        'Quick, light steps',
                        'Keep core tight',
                        'Maintain good posture',
                    ],
                    progressions: [
                        'Increase speed',
                        'Add ball touches between',
                        'Lateral movements',
                        'Backwards movements',
                    ],
                },

                // TECHNICAL DRILLS
                {
                    id: 'juggling-challenge',
                    name: 'Juggling Challenge',
                    category: 'technical',
                    difficulty: 'beginner',
                    description: 'Build touch, coordination, and ball mastery',
                    instructions: [
                        'Start with the ball in your hands',
                        'Drop and control with your foot',
                        'Keep the ball in the air using feet, thighs, chest, head',
                        'Try to beat your personal record',
                        'Challenge: alternate feet',
                    ],
                    icon: '⚽',
                    color: '#10b981',
                    duration: 10,
                    playersNeeded: '1+',
                    spaceRequired: 'Minimal',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['1 ball per player'],
                    keyPoints: [
                        'Relax and stay balanced',
                        'Use your laces for control',
                        'Soft touches',
                        'Keep ball at waist height',
                    ],
                    progressions: [
                        'Alternate feet only',
                        'Add trick moves',
                        'Sit down while juggling',
                        'Juggle with weaker foot only',
                    ],
                },

                // SMALL-SIDED GAMES
                {
                    id: '3v3-mini-goals',
                    name: '3v3 with Mini Goals',
                    category: 'smallSided',
                    difficulty: 'intermediate',
                    description: 'Game-realistic training with maximum touches',
                    instructions: [
                        'Set up a 20x15m pitch with mini goals at each end',
                        'Play 3v3 - no goalkeepers',
                        'Normal soccer rules apply',
                        'Play 5-minute games',
                        'Rotate teams',
                    ],
                    icon: '🏃',
                    color: '#ec4899',
                    duration: 20,
                    playersNeeded: '6+',
                    spaceRequired: '20x15m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['4 cones', '2 mini goals or cones', '1 ball', 'Colored bibs'],
                    keyPoints: [
                        'Constant movement',
                        'Quick transitions',
                        'Support teammates',
                        'Defend as a unit',
                    ],
                    progressions: [
                        'Add touch restrictions',
                        'Must complete 5 passes before scoring',
                        'Odd-number teams (3v2, 4v3)',
                        'Add conditions (must score with weaker foot)',
                    ],
                },

                // COGNITIVE FITNESS (22 drills)
                {
                    id: 'touch-or-turn-audio-cue',
                    name: 'Touch or Turn with Audio Cue',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'intermediate',
                    description: 'React to audio cues to touch cones or change direction — builds reaction time, focus, and decision making under pressure',
                    instructions: [
                        'Ensure the volume on your device is turned up',
                        'Set up 4 colored cones in a square formation (numbered 1-4)',
                        'Stand in the center of the cones',
                        'If you hear a NUMBER, squat and touch the associated cone',
                        'If you hear a DIRECTION, shuffle 180 degrees in that direction around the cones',
                        'Complete 3 sets of 30 seconds with 30 seconds rest between sets',
                    ],
                    icon: '🧠',
                    color: '#6366f1',
                    duration: 3,
                    playersNeeded: '1',
                    spaceRequired: '5x5m',
                    videoUrl: 'CTpkhb_iCGA',
                    equipment: ['4 colored cones', 'Phone or speaker for audio cues'],
                    keyPoints: [
                        'Quick decision making between touch vs turn',
                        'Maintain athletic stance throughout',
                        'Stay light on your feet',
                        'Focus and concentration essential',
                        'When facing opposite direction, cone numbers do NOT change',
                    ],
                    progressions: [
                        'Shuffle in the OPPOSITE direction from the audio cue',
                        'Increase speed of audio cues',
                        'Move cones further apart',
                        'Add more complex movements (burpee before touching)',
                        'Decrease rest time between sets',
                    ],
                    benefits: [
                        'Sharpens reaction time and split-second decision making',
                        'Improves auditory processing and cognitive flexibility',
                        'Enhances explosive power and change of direction speed',
                        'Builds mental focus and concentration under pressure',
                        'Develops quick feet and athletic stance',
                        'Trains dual-task processing (hearing + moving)',
                    ],
                },
                {
                    id: 'wall-decision',
                    name: 'Wall Decision',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'beginner',
                    description: 'Pass to wall → trap rebound → 1-touch pass → repeat',
                    instructions: [
                        'Stand 2m from wall',
                        'Pass firmly with inside foot',
                        'Trap rebound with inside foot',
                        'Repeat 20x with both feet',
                    ],
                    icon: '🧠',
                    color: '#6366f1',
                    duration: 10,
                    playersNeeded: '1',
                    spaceRequired: '2m from wall',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Wall', 'Ball'],
                    keyPoints: [
                        'First touch = decision',
                        'Head up after trap',
                        'Use both feet',
                        'Keep ball close',
                    ],
                    progressions: [
                        '1-touch pass only',
                        'Trap with outside foot',
                        'Add fake shot before pass',
                        'Pass with weaker foot',
                    ],
                },
                {
                    id: 'scan-and-react',
                    name: 'Scan & React',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'beginner',
                    description: '3 cones behind you → scan 360° → call color → sprint to it',
                    instructions: [
                        'Place 3 cones 5m behind you',
                        'Stand facing away',
                        'Scan 360° quickly',
                        'Call out color of cone behind',
                        'Sprint to it and trap',
                    ],
                    icon: '🧠',
                    color: '#6366f1',
                    duration: 10,
                    playersNeeded: '1',
                    spaceRequired: 'Open area',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['3 cones'],
                    keyPoints: [
                        'Head on swivel',
                        'Quick scan, not stare',
                        'Explode after call',
                    ],
                    progressions: [
                        'Add ball trap',
                        'Call wrong color → correct',
                        'Add fake sprint',
                    ],
                },
                {
                    id: 'color-call',
                    name: 'Color Call',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'beginner',
                    description: '4 colored cones → phone shouts color → first touch to cone',
                    instructions: [
                        'Place 4 cones around you',
                        'Hold ball in center',
                        'Phone shouts color',
                        'First touch toward cone',
                        'Pass to wall',
                    ],
                    icon: '🧠',
                    color: '#6366f1',
                    duration: 10,
                    playersNeeded: '1',
                    spaceRequired: 'Open area',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['4 colored cones', 'Phone'],
                    keyPoints: [
                        'React before thinking',
                        'Use inside foot',
                        'Head up',
                    ],
                    progressions: [
                        '1-touch only',
                        'Add fake touch',
                        'Use weaker foot',
                    ],
                },
                {
                    id: '1v0-chaos-box',
                    name: '1v0 Chaos Box',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'intermediate',
                    description: 'Dribble → fake → turn → pass to wall → repeat',
                    instructions: [
                        'Set up 4x4m box',
                        'Start with ball',
                        'Dribble → fake shot → turn → pass to wall',
                        'Receive rebound → repeat opposite direction',
                    ],
                    icon: '🧠',
                    color: '#6366f1',
                    duration: 15,
                    playersNeeded: '1',
                    spaceRequired: '4x4m box',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['4 cones', 'Ball', 'Wall'],
                    keyPoints: [
                        'Chain actions',
                        'No pause',
                        'Use both feet',
                    ],
                    progressions: [
                        'Add 1-touch pass',
                        'Fake with shoulder',
                        'Add step-over',
                    ],
                },
                {
                    id: 'random-gate',
                    name: 'Random Gate',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'intermediate',
                    description: 'Dribble freely → timer beeps → explode through random gate',
                    instructions: [
                        'Set up 6 gates (2m wide)',
                        'Dribble slowly in area',
                        'Timer beeps every 5–10 sec',
                        'Explode through random gate',
                        'Pass to wall',
                    ],
                    icon: '🧠',
                    color: '#6366f1',
                    duration: 15,
                    playersNeeded: '1',
                    spaceRequired: '10x10m area',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['6 small gates', 'Phone timer'],
                    keyPoints: [
                        'Explode on cue',
                        'Change direction fast',
                        'Head up',
                    ],
                    progressions: [
                        'Add ball trap at gate',
                        'Shorten beep interval',
                        'Add defender shadow',
                    ],
                },
                {
                    id: 'shadow-1v1',
                    name: 'Shadow 1v1',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'advanced',
                    description: 'Watch Neymar clip → pause at decision → copy move in 3 sec',
                    instructions: [
                        'Play 1v1 clip (Neymar/Messi)',
                        'Pause at moment of decision',
                        'Copy move exactly',
                        'Pass to wall',
                    ],
                    icon: '🧠',
                    color: '#6366f1',
                    duration: 10,
                    playersNeeded: '1',
                    spaceRequired: 'Open area',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone', 'Ball', 'Wall'],
                    keyPoints: [
                        'Match timing',
                        'Use same foot',
                        'Explode after move',
                    ],
                    progressions: [
                        'Mirror move',
                        'Add defender shadow',
                        'Do in game',
                    ],
                },
                {
                    id: 'plank-shoulder-taps',
                    name: 'Plank + Shoulder Taps',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'beginner',
                    description: 'Plank → tap opposite shoulder',
                    instructions: [
                        'Hold plank',
                        'Tap opposite shoulder with one hand',
                        'Keep hips stable',
                        '3x40 sec',
                    ],
                    icon: '💪',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['None'],
                    keyPoints: [
                        'No hip rock',
                        'Core tight',
                        'Breathe',
                    ],
                    progressions: [
                        'Add push-up',
                        'Hold 2 min',
                        'Add leg lift',
                    ],
                },
                {
                    id: 'dead-bugs',
                    name: 'Dead Bugs',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'beginner',
                    description: 'Lie on back → extend opposite arm/leg slowly',
                    instructions: [
                        'Lie on back, knees up',
                        'Extend opposite arm/leg',
                        'Keep lower back pressed',
                        '3x12/side',
                    ],
                    icon: '💪',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['None'],
                    keyPoints: [
                        'Slow control',
                        'No arch in back',
                        'Breathe out',
                    ],
                    progressions: [
                        'Add ball hold',
                        'Hold 5 sec',
                        'Add rotation',
                    ],
                },
                {
                    id: 'russian-twists-ball',
                    name: 'Russian Twists (with ball)',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'intermediate',
                    description: 'Sit → twist + pass ball to wall',
                    instructions: [
                        'Sit with knees bent',
                        'Hold ball',
                        'Twist and pass to wall',
                        '3x20',
                    ],
                    icon: '💪',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Ball'],
                    keyPoints: [
                        'Rotate from core',
                        'Keep chest up',
                        'Fast twist',
                    ],
                    progressions: [
                        'Feet off ground',
                        'Add medicine ball',
                        '1-touch pass',
                    ],
                },
                {
                    id: 'side-plank-hip-dip',
                    name: 'Side Plank + Hip Dip',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'intermediate',
                    description: 'Side plank → dip hip',
                    instructions: [
                        'Side plank on elbow',
                        'Dip hip to floor',
                        'Return to top',
                        '3x10/side',
                    ],
                    icon: '💪',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['None'],
                    keyPoints: [
                        'No sag',
                        'Shoulder over elbow',
                        'Control dip',
                    ],
                    progressions: [
                        'Add leg lift',
                        'Hold dip 3 sec',
                        'Add rotation',
                    ],
                },
                {
                    id: 'bird-dog',
                    name: 'Bird Dog',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'beginner',
                    description: 'On all 4s → extend opposite arm/leg',
                    instructions: [
                        'On hands and knees',
                        'Extend opposite arm/leg',
                        'Hold 3 sec',
                        '3x10/side',
                    ],
                    icon: '💪',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['None'],
                    keyPoints: [
                        'No arch in back',
                        'Look down',
                        'Slow control',
                    ],
                    progressions: [
                        'Add ball tap',
                        'Hold 10 sec',
                        'Add rotation',
                    ],
                },
                {
                    id: 'single-leg-glute-bridge',
                    name: 'Single-Leg Glute Bridge',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'beginner',
                    description: 'Lie on back → lift hips on 1 leg',
                    instructions: [
                        'Lie on back, one knee bent',
                        'Lift hips on one leg',
                        'Hold 2 sec',
                        '3x12/leg',
                    ],
                    icon: '🦵',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['None'],
                    keyPoints: [
                        'Squeeze glute',
                        'No hip drop',
                        'Slow lower',
                    ],
                    progressions: [
                        'Add ball under foot',
                        'Hold 5 sec',
                        'Add march',
                    ],
                },
                {
                    id: 'lateral-bounds',
                    name: 'Lateral Bounds',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'intermediate',
                    description: 'Jump side to side → stick landing',
                    instructions: [
                        'Jump laterally',
                        'Land on one leg',
                        'Stick 1 sec',
                        '3x10/side',
                    ],
                    icon: '🦵',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Open area',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['None'],
                    keyPoints: [
                        'Soft landing',
                        'Knee over toe',
                        'Explode',
                    ],
                    progressions: [
                        'Add ball trap',
                        'Increase distance',
                        'Add cut',
                    ],
                },
                {
                    id: 'calf-hops',
                    name: 'Calf Hops',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'beginner',
                    description: 'Quick small hops on toes',
                    instructions: [
                        'Stand on toes',
                        'Small quick hops',
                        'Stay light',
                        '3x20',
                    ],
                    icon: '🦵',
                    color: '#6366f1',
                    duration: 3,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['None'],
                    keyPoints: [
                        'Ankles only',
                        'Fast ground contact',
                        'No heel touch',
                    ],
                    progressions: [
                        'Add single leg',
                        'Add sprint after',
                        'Add direction change',
                    ],
                },
                {
                    id: 'box-step-ups',
                    name: 'Box Step-Ups',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'beginner',
                    description: 'Step up slow → drive knee',
                    instructions: [
                        'Step up with one leg',
                        'Drive opposite knee',
                        'Lower slow',
                        '3x12/leg',
                    ],
                    icon: '🦵',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Low bench or step'],
                    keyPoints: [
                        'Knee over toe',
                        'Drive up',
                        'Control down',
                    ],
                    progressions: [
                        'Add ball hold',
                        'Increase height',
                        'Add jump',
                    ],
                },
                {
                    id: 'push-up-ball-roll',
                    name: 'Push-Up + Ball Roll',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'beginner',
                    description: 'Push-up → roll ball side to side',
                    instructions: [
                        'Push-up position',
                        'Roll ball side to side',
                        'Keep core tight',
                        '3x10',
                    ],
                    icon: '💪',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Ball'],
                    keyPoints: [
                        'No sag',
                        'Slow roll',
                        'Breathe',
                    ],
                    progressions: [
                        'Add clap',
                        'Add rotation',
                        'Single arm roll',
                    ],
                },
                {
                    id: 'superman-holds',
                    name: 'Superman Holds',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'beginner',
                    description: 'Lie face down → lift arms/legs',
                    instructions: [
                        'Lie face down',
                        'Lift arms and legs',
                        'Hold 30 sec',
                        '3x',
                    ],
                    icon: '💪',
                    color: '#6366f1',
                    duration: 3,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['None'],
                    keyPoints: [
                        'Squeeze back',
                        'Look down',
                        'Breathe',
                    ],
                    progressions: [
                        'Add flutter',
                        'Hold 60 sec',
                        'Add rotation',
                    ],
                },
                {
                    id: 'ball-mastery',
                    name: 'Ball Mastery',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'beginner',
                    description: 'Toe taps → pull-push → V-turns → inside-out',
                    instructions: [
                        'Stand with ball',
                        'Toe taps 20x',
                        'Pull-push 20x',
                        'V-turns 10x/side',
                        'Inside-out 10x/side',
                    ],
                    icon: '⚽',
                    color: '#6366f1',
                    duration: 10,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Ball'],
                    keyPoints: [
                        'Light touch',
                        'Head up',
                        'Use both feet',
                    ],
                    progressions: [
                        'Add speed',
                        'Add fake',
                        'Add wall pass',
                    ],
                },
                {
                    id: 'ladder-slow',
                    name: 'Ladder (slow)',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'beginner',
                    description: 'In-out → icky shuffle → side steps (60% speed)',
                    instructions: [
                        'Slow in-out',
                        'Icky shuffle',
                        'Side steps',
                        'Focus on foot placement',
                    ],
                    icon: '⚡',
                    color: '#6366f1',
                    duration: 8,
                    playersNeeded: '1',
                    spaceRequired: 'Ladder',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Agility ladder'],
                    keyPoints: [
                        'Light feet',
                        'Knees up',
                        'No rush',
                    ],
                    progressions: [
                        'Increase speed',
                        'Add ball',
                        'Add direction change',
                    ],
                },
                {
                    id: 'cone-square',
                    name: 'Cone Square',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'intermediate',
                    description: 'Dribble → roll → cut → pass to wall',
                    instructions: [
                        'Dribble to cone',
                        'Roll ball',
                        'Cut inside',
                        'Pass to wall',
                    ],
                    icon: '🎯',
                    color: '#6366f1',
                    duration: 10,
                    playersNeeded: '1',
                    spaceRequired: '4 cones',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['4 cones', 'Wall'],
                    keyPoints: [
                        'Close control',
                        'Head up',
                        'Use both feet',
                    ],
                    progressions: [
                        'Add fake',
                        '1-touch pass',
                        'Add defender shadow',
                    ],
                },
                {
                    id: 'dynamic-warmup',
                    name: 'Dynamic Warm-Up + Stretch',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'beginner',
                    description: 'Jog + arm circles → high knees → leg swings → stretch',
                    instructions: [
                        'Light jog 2 min',
                        'Arm circles 20x',
                        'High knees 20 sec',
                        'Leg swings 10x/leg',
                        'Calf/quad stretch',
                    ],
                    icon: '🏃',
                    color: '#6366f1',
                    duration: 10,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['None'],
                    keyPoints: [
                        'Gradual increase',
                        'Breathe',
                        'Loosen hips',
                    ],
                    progressions: [
                        'Add lunges',
                        'Add dynamic stretch',
                        'Add sprint',
                    ],
                },

                // Additional Cognitive Fitness Drills
                {
                    id: 'color-reaction-sprint',
                    name: 'Color Reaction Sprint',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'beginner',
                    description: 'Sprint on color flash — improves visual processing and explosive reaction',
                    instructions: [
                        'Mark 10m sprint line',
                        'Start at baseline',
                        'App flashes color (e.g., green = sprint)',
                        'React and sprint on cue',
                        '3 sets of 8 reps, 20s rest',
                    ],
                    icon: '🎨',
                    color: '#6366f1',
                    duration: 4,
                    playersNeeded: '1',
                    spaceRequired: '10m line',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone', 'Markers'],
                    keyPoints: [
                        'Explode on first flash',
                        'Stay low and ready',
                        'Reset quickly',
                    ],
                    progressions: [
                        'Add direction (left/right colors)',
                        'Reduce flash time to 0.5s',
                        'Combine with ball trap',
                    ],
                },
                {
                    id: 'arrow-direction-change',
                    name: 'Arrow Direction Change',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'intermediate',
                    description: 'Shuffle based on arrow direction — enhances spatial awareness and agility',
                    instructions: [
                        'Stand in center',
                        'App shows arrow (↑ = forward shuffle)',
                        'Shuffle 180° or touch direction',
                        '10 reps, 1 min rounds x 3',
                    ],
                    icon: '➡️',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: '5x5m grid',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Quick read and move',
                        'Maintain balance',
                        'Use peripheral vision',
                    ],
                    progressions: [
                        'Opposite direction arrows',
                        'Add number for cone touch',
                        'Increase shuffle distance',
                    ],
                },
                {
                    id: 'number-recall-pass',
                    name: 'Number Recall Pass',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'advanced',
                    description: 'Pass after hearing number sequence — boosts working memory and precision',
                    instructions: [
                        'App says 3-number sequence',
                        'Repeat by passing (e.g., 1-2-3 = short-medium-long)',
                        '5 reps, 45s rest x 4',
                    ],
                    icon: '🔢',
                    color: '#6366f1',
                    duration: 6,
                    playersNeeded: '1',
                    spaceRequired: 'Wall or partner',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone', 'Ball'],
                    keyPoints: [
                        'Memorize first',
                        'Vary pass weight',
                        'Head up post-pass',
                    ],
                    progressions: [
                        '4-number sequences',
                        'Reverse order',
                        'Add movement',
                    ],
                },
                {
                    id: 'visual-scanning-grid',
                    name: 'Visual Scanning Grid',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'intermediate',
                    description: 'Scan grid for highlighted cell — improves peripheral vision and focus',
                    instructions: [
                        'App shows 3x3 grid, highlights one',
                        'Scan and point/touch',
                        '20 reps, 2 min rounds x 3',
                    ],
                    icon: '📊',
                    color: '#6366f1',
                    duration: 4,
                    playersNeeded: '1',
                    spaceRequired: 'Open',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Wide field of view',
                        'Quick locate',
                        'No head turn',
                    ],
                    progressions: [
                        '4x4 grid',
                        'Timed (under 2s)',
                        'Add audio cue',
                    ],
                },
                {
                    id: 'decision-tree-drill',
                    name: 'Decision Tree Drill',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'advanced',
                    description: 'Branch decisions on cue (e.g., color = left pass) — simulates game choices',
                    instructions: [
                        'Set cone branches',
                        'Cue dictates path',
                        'Follow and pass',
                        '10 reps x 3',
                    ],
                    icon: '🌳',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: '5x5m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone', 'Cones'],
                    keyPoints: [
                        'Read cue instantly',
                        'Commit to branch',
                        'Adapt mid-move',
                    ],
                    progressions: [
                        'Dual cues (color + number)',
                        'Add fake branch',
                        'Team version',
                    ],
                },
                {
                    id: 'inhibition-stop-go',
                    name: 'Inhibition Stop-Go',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'beginner',
                    description: 'Go on green, stop on red — trains impulse control and reaction inhibition',
                    instructions: [
                        'Sprint on "go" cue',
                        'Stop immediately on "stop"',
                        '5 reps, 30s rest x 4',
                    ],
                    icon: '🚦',
                    color: '#6366f1',
                    duration: 3,
                    playersNeeded: '1',
                    spaceRequired: '10m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Full stop, no creep',
                        'Ready position',
                        'Reset fast',
                    ],
                    progressions: [
                        'Random stop timing',
                        'Add direction',
                        'With ball',
                    ],
                },
                {
                    id: 'memory-match-reaction',
                    name: 'Memory Match Reaction',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'intermediate',
                    description: 'Match pattern then react — enhances short-term memory and speed',
                    instructions: [
                        'App shows pattern (e.g., red-blue)',
                        'Repeat pattern touch',
                        'React with sprint',
                        '8 reps x 3',
                    ],
                    icon: '🧩',
                    color: '#6366f1',
                    duration: 6,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Memorize accurately',
                        'Smooth repeat',
                        'Explode after',
                    ],
                    progressions: [
                        'Longer patterns',
                        'Reverse match',
                        'Add physical load',
                    ],
                },
                {
                    id: 'spatial-awareness-shuffle',
                    name: 'Spatial Awareness Shuffle',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'intermediate',
                    description: 'Shuffle to marked spot on cue — builds body positioning and awareness',
                    instructions: [
                        'Mark 4 spots',
                        'Cue dictates shuffle spot',
                        'Quick move and return',
                        '15 reps x 2',
                    ],
                    icon: '📍',
                    color: '#6366f1',
                    duration: 4,
                    playersNeeded: '1',
                    spaceRequired: '5x5m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone', 'Markers'],
                    keyPoints: [
                        'Efficient path',
                        'Stay balanced',
                        'Scan ahead',
                    ],
                    progressions: [
                        'Random spots',
                        'Add obstacle',
                        'With ball control',
                    ],
                },
                {
                    id: 'audio-direction-pivot',
                    name: 'Audio Direction Pivot',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'beginner',
                    description: 'Pivot on direction call — improves auditory processing and footwork',
                    instructions: [
                        'Stand ready',
                        'Audio calls "left" or "right"',
                        'Pivot 90°',
                        '20 reps, 1 min rounds',
                    ],
                    icon: '🔊',
                    color: '#6366f1',
                    duration: 3,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Sharp pivot',
                        'Plant foot',
                        'Ready for next',
                    ],
                    progressions: [
                        'Add forward/back',
                        'Combine with color',
                        'Increase speed',
                    ],
                },
                {
                    id: 'focus-lock-drill',
                    name: 'Focus Lock Drill',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'advanced',
                    description: 'Ignore distractors, react to target — trains selective attention',
                    instructions: [
                        'App shows distractors + target',
                        'React only to target',
                        'Sprint or touch',
                        '10 reps x 3',
                    ],
                    icon: '🎯',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Open',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Block noise',
                        'Target only',
                        'Consistent reaction',
                    ],
                    progressions: [
                        'More distractors',
                        'Faster pace',
                        'Add movement',
                    ],
                },
                {
                    id: 'cognitive-agility-ladder',
                    name: 'Cognitive Agility Ladder',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'intermediate',
                    description: 'Ladder steps on cue — combines footwork with cognitive load',
                    instructions: [
                        'Cue dictates step pattern',
                        'Execute in ladder',
                        '3 rounds x 20s',
                    ],
                    icon: '🪜',
                    color: '#6366f1',
                    duration: 6,
                    playersNeeded: '1',
                    spaceRequired: 'Ladder',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Agility ladder', 'Phone'],
                    keyPoints: [
                        'Sync cue to foot',
                        'Light contact',
                        'Head up',
                    ],
                    progressions: [
                        'Random patterns',
                        'Add color code',
                        'Increase speed',
                    ],
                },
                {
                    id: 'reaction-ball-drop',
                    name: 'Reaction Ball Drop',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'beginner',
                    description: 'Catch ball on beep — improves hand-eye coordination and timing',
                    instructions: [
                        'Drop ball on cue',
                        'Catch before bounce',
                        '10 reps x 3',
                    ],
                    icon: '🏀',
                    color: '#6366f1',
                    duration: 4,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Reaction ball', 'Phone'],
                    keyPoints: [
                        'Watch ball path',
                        'Soft hands',
                        'Quick reset',
                    ],
                    progressions: [
                        'Higher drop',
                        'Add direction cue',
                        'Two balls',
                    ],
                },
                {
                    id: 'mental-flexibility-switch',
                    name: 'Mental Flexibility Switch',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'advanced',
                    description: 'Switch task on cue (sprint vs shuffle) — trains adaptability',
                    instructions: [
                        'Cue changes movement type',
                        'Switch instantly',
                        '15 reps x 2',
                    ],
                    icon: '🔄',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: '5m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Adapt fast',
                        'No hesitation',
                        'Stay controlled',
                    ],
                    progressions: [
                        'Cue mid-movement',
                        'Add ball',
                        'Team sync',
                    ],
                },
                {
                    id: 'beep-test-variation',
                    name: 'Beep Test Variation',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'intermediate',
                    description: 'Shuttle run on beep with random stops — builds endurance + cognition',
                    instructions: [
                        '20m shuttles on beep',
                        'Random stop cues',
                        'Level 1-5, 2 min',
                    ],
                    icon: '🔔',
                    color: '#6366f1',
                    duration: 8,
                    playersNeeded: '1',
                    spaceRequired: '20m shuttle',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Pace to beep',
                        'Quick stop',
                        'Recover fast',
                    ],
                    progressions: [
                        'Faster beeps',
                        'Add direction',
                        'With ball',
                    ],
                },
                {
                    id: 'pattern-recognition-pass',
                    name: 'Pattern Recognition Pass',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'intermediate',
                    description: 'Pass following pattern cue — enhances anticipation',
                    instructions: [
                        'Cue pattern (e.g., low-high-low)',
                        'Execute passes',
                        '10 reps x 3',
                    ],
                    icon: '🎼',
                    color: '#6366f1',
                    duration: 6,
                    playersNeeded: '1',
                    spaceRequired: 'Wall',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone', 'Ball'],
                    keyPoints: [
                        'Anticipate next',
                        'Consistent weight',
                        'Head up',
                    ],
                    progressions: [
                        'Longer patterns',
                        'Reverse',
                        'Add fake',
                    ],
                },
                {
                    id: 'dual-task-juggle',
                    name: 'Dual Task Juggle',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'advanced',
                    description: 'Juggle while reacting to cues — multitask coordination',
                    instructions: [
                        'Juggle on go cue',
                        'Stop or switch on stop',
                        '1 min rounds x 4',
                    ],
                    icon: '🤹',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone', 'Ball'],
                    keyPoints: [
                        'Focus split',
                        'Maintain rhythm',
                        'Adapt seamlessly',
                    ],
                    progressions: [
                        'Add direction',
                        'Faster cues',
                        'Two balls',
                    ],
                },
                {
                    id: 'anticipation-shadow',
                    name: 'Anticipation Shadow',
                    category: 'cognitive',
                    section: 'soccer',
                    difficulty: 'advanced',
                    description: 'Shadow pro move with predictive cues — improves foresight',
                    instructions: [
                        'Watch clip preview',
                        'Cue predicts next move',
                        'Shadow execute',
                        '5 reps x 3',
                    ],
                    icon: '👤',
                    color: '#6366f1',
                    duration: 7,
                    playersNeeded: '1',
                    spaceRequired: 'Open',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Predict cue',
                        'Match timing',
                        'Fluid motion',
                    ],
                    progressions: [
                        'No preview',
                        'Random pros',
                        'Add ball',
                    ],
                },
                {
                    id: 'error-correction-drill',
                    name: 'Error Correction Drill',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'intermediate',
                    description: 'Correct wrong cue — trains error detection and adjustment',
                    instructions: [
                        'Cue wrong direction',
                        'Correct and move right',
                        '12 reps x 2',
                    ],
                    icon: '✅',
                    color: '#6366f1',
                    duration: 4,
                    playersNeeded: '1',
                    spaceRequired: '5x5m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone', 'Cones'],
                    keyPoints: [
                        'Spot error fast',
                        'Adjust smoothly',
                        'Stay positive',
                    ],
                    progressions: [
                        'Faster errors',
                        'Multi-errors',
                        'With speed',
                    ],
                },
                {
                    id: 'cognitive-endurance-run',
                    name: 'Cognitive Endurance Run',
                    category: 'cognitive',
                    section: 'fitness',
                    difficulty: 'advanced',
                    description: 'Run laps with accumulating cues — sustains focus over time',
                    instructions: [
                        'Jog laps',
                        'Cues increase every lap',
                        '5 laps, react each',
                    ],
                    icon: '🏃‍♂️',
                    color: '#6366f1',
                    duration: 10,
                    playersNeeded: '1',
                    spaceRequired: 'Track',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Maintain pace',
                        'Ignore fatigue',
                        'Consistent reactions',
                    ],
                    progressions: [
                        'Longer duration',
                        'Complex cues',
                        'Hill variation',
                    ],
                },
                {
                    id: 'visual-inhibition-filter',
                    name: 'Visual Inhibition Filter',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'beginner',
                    description: 'Ignore flashing distractors, react to steady light — sharpens attention',
                    instructions: [
                        'React to steady cue only',
                        'Ignore flashes',
                        '20 reps x 2',
                    ],
                    icon: '💡',
                    color: '#6366f1',
                    duration: 3,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Filter noise',
                        'Steady focus',
                        'Quick ignore',
                    ],
                    progressions: [
                        'More distractors',
                        'Faster steady',
                        'Add audio',
                    ],
                },
                {
                    id: 'sequence-prediction',
                    name: 'Sequence Prediction',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'intermediate',
                    description: 'Predict next in sequence — builds pattern recognition',
                    instructions: [
                        'App shows sequence',
                        'Predict and react',
                        '8 sequences x 3',
                    ],
                    icon: '🔮',
                    color: '#6366f1',
                    duration: 5,
                    playersNeeded: '1',
                    spaceRequired: 'Open',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Spot pattern',
                        'Anticipate',
                        'Confirm reaction',
                    ],
                    progressions: [
                        'Complex sequences',
                        'Time pressure',
                        'Physical response',
                    ],
                },
                {
                    id: 'multi-sensory-cue',
                    name: 'Multi-Sensory Cue',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'advanced',
                    description: 'React to combined visual + audio — integrates senses',
                    instructions: [
                        'Dual cue (color + sound)',
                        'Match both for action',
                        '15 reps x 2',
                    ],
                    icon: '🎭',
                    color: '#6366f1',
                    duration: 4,
                    playersNeeded: '1',
                    spaceRequired: '5x5m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Process both',
                        'Prioritize match',
                        'Seamless integrate',
                    ],
                    progressions: [
                        'Conflicting cues',
                        'Faster dual',
                        'Add touch',
                    ],
                },
                {
                    id: 'mental-rotation-scan',
                    name: 'Mental Rotation Scan',
                    category: 'cognitive',
                    section: 'intelligence',
                    difficulty: 'intermediate',
                    description: 'Identify rotated shape — enhances mental flexibility',
                    instructions: [
                        'App rotates shape',
                        'Identify match',
                        'React with point',
                        '20 reps x 3',
                    ],
                    icon: '🔄',
                    color: '#6366f1',
                    duration: 6,
                    playersNeeded: '1',
                    spaceRequired: 'Any',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Visualize rotation',
                        'Quick match',
                        'No overthink',
                    ],
                    progressions: [
                        '3D rotation',
                        'Time limit',
                        'Add movement',
                    ],
                },
                {
                    id: 'cue-inhibition-challenge',
                    name: 'Cue Inhibition Challenge',
                    category: 'cognitive',
                    section: 'agility',
                    difficulty: 'advanced',
                    description: 'Resist automatic response to inhibitory cues — builds self-control',
                    instructions: [
                        'Go on standard, inhibit on special',
                        'Sprint or hold',
                        '12 reps x 2',
                    ],
                    icon: '⛔',
                    color: '#6366f1',
                    duration: 3,
                    playersNeeded: '1',
                    spaceRequired: '10m',
                    videoUrl: 'Z2ckosM2pWg',
                    equipment: ['Phone'],
                    keyPoints: [
                        'Override impulse',
                        'Strong hold',
                        'Release clean',
                    ],
                    progressions: [
                        'Shorter hold',
                        'More inhibits',
                        'With load',
                    ],
                },
            ];

            // Load saved completions from localStorage
            if (process.client)
            {
                const saved = localStorage.getItem('instinctfc-completions');
                if (saved)
                {
                    try
                    {
                        this.completions = JSON.parse(saved).map((c: any) => ({
                            ...c,
                            completedAt: new Date(c.completedAt),
                        }));
                    } catch (e)
                    {
                        console.error('Error loading completions:', e);
                    }
                }
            }
        },

        markComplete(drillId: string, notes?: string, rating?: number)
        {
            const completion: DrillCompletion = {
                drillId,
                completedAt: new Date(),
                notes,
                rating,
            };

            this.completions.push(completion);
            this.saveCompletions();
        },

        saveCompletions()
        {
            if (process.client)
            {
                localStorage.setItem('instinctfc-completions', JSON.stringify(this.completions));
            }
        },

        clearAllData()
        {
            this.completions = [];
            if (process.client)
            {
                localStorage.removeItem('instinctfc-completions');
            }
        },
    },
});
